---

- name: Copying ssl keys
  copy: 
    content: "{{ item.key }}"
    dest: "{{ openssl_keys_path }}/{{ item.name }}.key"
    owner: root
    group: root
    mode: 0600
  with_items: openssl_keys
  tags:
    - system
    - openssl
    - copy

- name: Copying ssl certs
  copy:
    content: "{{ item.cert }}"
    dest: "{{ openssl_certs_path }}/{{ item.name }}.crt"
    owner: root
    group: root
    mode: 0644
  with_items: openssl_keys
  tags:
    - system
    - openssl
    - copy

- name: Copying merged key and certs
  template:
    src: 'merge-key-cert.pem.j2'
    dest: "{{ openssl_keys_path }}/{{ item.name }}.pem"
    owner: root
    group: root
    mode: 0600
  when: openssl_merge_files
  with_items: openssl_keys
  tags:
    - system
    - openssl
    - copy

- name: Copying owned ca cert
  copy: 
    content: "{{ item.ca }}"
    dest: "/usr/local/share/ca-certificates/{{ item.name }}.crt"
    owner: root
    group: root
    mode: 0644
  with_items: openssl_ca
  register: ca
  tags:
    - system
    - openssl
    - ca