---

- name: Installing packages with APT
  apt:
    pkg: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - openssl

- name: Installing packages with PACMAN
  pacman:
    pkg: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'pacman'
  with_items:
    - openssl

- name: Installing packages with YUM
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'yum'
  with_items:
    - openssl

- name: Creating certs dir
  include: create_dir.yml
  vars:
    item: "{{ openssl_certs_path }}"
    mode: "0755"

- name: Creating keys dir
  include: create_dir.yml
  vars:
    item: "{{ openssl_keys_path }}"
    mode: "0700"

- name: Creating csrs dir
  when: openssl_generate_csr
  include: create_dir.yml
  vars:
    item: "{{ openssl_csrs_path }}"
    mode: "0750"

